BUCKET: gs://pcst-ad

CONDITIONS:
  - Control
  - Disease

CELLTYPES:
  - Neuron
  - Astrocyte
  - Microglia

CONTAINERS:
  counts: us-central1-docker.pkg.dev/starlit-cycle-479722-q0/pcst-ad-containers/counts:latest
