executor: googlebatch

googlebatch-region: us-central1
googlebatch-project: starlit-cycle-479722-q0

googlebatch-machine-type: e2-highmem-2
googlebatch-image-family: rocky-linux-8
googlebatch-image-project: rocky-linux-cloud


googlebatch-memory: 13000
googlebatch-cpu-milli: 2000
googlebatch-boot-disk-gb: 50

software-deployment-method:
  - conda

default-storage-provider: gcs
default-storage-prefix: gs://pcst-ad
storage-gcs-project: starlit-cycle-479722-q0

preemptible-rules:
  - counts
  - fava
  - network
  - scppin
  - gsea
  - heatmap

jobs: 5
latency-wait: 60
