executor: googlebatch
googlebatch-project: starlit-cycle-479722-q0
googlebatch-region: us-central1
container-image: docker://mambaorg/micromamba:latest
software-deployment-method:
  - conda
  - apptainer
default-storage-provider: gcs
default-storage-prefix: gs://pcst-ad
storage-gcs-project: starlit-cycle-479722-q0
default-resources:
  - runtime=60
  - mem_mb=4000
  - disk_mb=10000
preemptible-rules:
  - counts
  - fava
  - merge
  - stringdb
jobs: 10
latency-wait: 60

